import {
  createApi,
  BaseQueryFn,
  FetchArgs,
  FetchBaseQueryError,
} from "@reduxjs/toolkit/query/react";
import { baseQueryWithReauth } from "../../lib/baseQueryWithReauth";
import { customerBaseQuery } from "../../lib/customerApiConfigs";

const dynamicBaseQuery: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
  if ((extraOptions as any)?.isCustomer) {
    return customerBaseQuery(args, api, extraOptions);
  }
  return baseQueryWithReauth(args, api, extraOptions);
};

export const apiSlice = createApi({
  reducerPath: "api",
  baseQuery: dynamicBaseQuery,
  tagTypes: [
    "Bike",
    "BikeList",
    "Quotation",
    "Branch",
    "BranchManager",
    "VisitorCount",
    "VisitorStats",
    "User",
    "Admin",
    "Customer",
    "ServiceAdmin",
    "BranchAdmin",
    "Staff",
    "Vehicle",
    "Stock",
    "ServiceBooking",
    "SetupProgress",
    "Comparison",
    "BikeImage",
    "BikeImageList",
    "StockConcept",
    "AdminBooking",
    "AdminStats",
    "UpcomingAppointments",
    "CustomerVehicle",
    "VehicleStats",
    "ServiceHistory",
    "CustomerStockVehicle",
    "CSVStock",
    "CSVStockList",
    "CSVBatch",
    "GetApproved",
    "GetApprovedStats",
    "ScanFleetProfile",
    "VAS",
    "CustomerActiveService",
    "BookingStats",
    "Availability",
    "ScanFleetActivation",
    "ContactMessages",
    "ContactMessage",
    "AccidentReport",
    "Leave",
    "LeaveBalance",
    "JobCard",
    "JobCardList",
    "JobCardInvoice",
    "JobCardCatalog",
    "JobCardCatalogItem",
    "JobCardInvoice",
    "PartAdmin",
    "Parts",
    "PartsBatch",
    "PartsStats",
    "CounterSale",
    "CounterSaleBatch",
    "CounterSaleDeletedBatch",
    "Me",
    "DataImportConfig",
    "DataImportDataset",
    "DataImportRow",
    "SalesTimeseries",
    "RagChat",
  ],
  endpoints: () => ({}),
});
